// Codegen: build public/adaptive-harvest.js from the SAME in-page extraction
// scripts the crawler runs (single source of truth — crawler and snippet can
// never drift apart). Run: `bun run scripts/build-harvest.ts`.
//
// The emitted bundle is a self-contained, opt-in harvester: included on a page
// (or lazy-loaded by the snippet later) it elects a sampled homepage visit,
// runs the extraction at idle, and POSTs the audit to /api/adaptive/inventory.
// It intentionally does NOT scroll the visitor's viewport (no UX disruption),
// so some lazy below-fold content may be missed vs the headless crawler.

import { writeFileSync } from "node:fs";
import { join } from "node:path";

import { CTAS_SCRIPT } from "../src/lib/tests/scripts/ctas";
import { SECTIONS_SCRIPT } from "../src/lib/tests/scripts/sections";
import { TRUST_SIGNALS_SCRIPT } from "../src/lib/tests/scripts/trustSignals";
import { PAGE_AUDIT_SCRIPT } from "../src/lib/tests/scripts/pageAudit";

const banner = `/* GENERATED by scripts/build-harvest.ts — do not edit by hand.
 * Rebuild after changing src/lib/tests/scripts/*: bun run scripts/build-harvest.ts
 */`;

// Each *_SCRIPT is a synchronous IIFE string: `(() => { ... })()` returning its
// result. We assign each to a var, assemble the inventory-relevant subset, and
// POST it. Everything is wrapped so nothing leaks to the page's global scope.
const bundle = `${banner}
(function () {
  "use strict";

  function findSelf() {
    if (document.currentScript) return document.currentScript;
    var s = document.getElementsByTagName("script");
    for (var i = s.length - 1; i >= 0; i--) {
      if ((s[i].src || "").indexOf("adaptive-harvest") !== -1) return s[i];
    }
    return null;
  }

  var self = findSelf();
  var base = "";
  try { base = self ? new URL(self.src, location.href).origin : location.origin; } catch (e) { base = location.origin; }
  var site = (self && self.getAttribute("data-site")) || location.hostname.replace(/^www\\./, "");
  var force = !!(self && self.getAttribute("data-force") === "1");
  // Opt-in: sweep-scroll to trigger lazy/below-fold content before extracting.
  // Off by default because it moves the viewport (UX). Enable with data-warmup="1".
  var warmup = !!(self && self.getAttribute("data-warmup") === "1");

  // Sample once per (site, page) per UTC day — inventory changes slowly, so one
  // harvest per page per day is plenty and keeps the cost off nearly every visit.
  function elected() {
    if (force) return true;
    try {
      var day = new Date().toISOString().slice(0, 10);
      var key = "angel_harvest:" + site + ":" + location.pathname + ":" + day;
      if (localStorage.getItem(key)) return false;
      localStorage.setItem(key, "1");
      return true;
    } catch (e) {
      return true;
    }
  }

  function harvest() {
    if (!warmup) { extract(); return; }
    // Gentle sweep: scroll through the page to trigger IntersectionObserver /
    // lazy content, then restore the visitor's original position and extract.
    try {
      var y0 = window.scrollY;
      var h = document.documentElement.scrollHeight;
      var steps = 6, i = 0;
      var iv = setInterval(function () {
        i++;
        try { window.scrollTo(0, (h / steps) * i); } catch (e) {}
        if (i >= steps) {
          clearInterval(iv);
          try { window.scrollTo(0, y0); } catch (e) {}
          setTimeout(extract, 250);
        }
      }, 60);
    } catch (e) {
      extract();
    }
  }

  function extract() {
    try {
      var ctas = ${CTAS_SCRIPT};
      var sections = ${SECTIONS_SCRIPT};
      var trust = ${TRUST_SIGNALS_SCRIPT};
      var audit = ${PAGE_AUDIT_SCRIPT};
      var payload = {
        site: site,
        url: location.href,
        path: location.pathname,
        audit: {
          url: location.href,
          ctas: ctas || [],
          sections: sections || [],
          trustSignals: (trust && trust.signals) || [],
          headings: (audit && audit.headings) || undefined,
        },
      };
      fetch(base + "/api/adaptive/inventory", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
        keepalive: true,
        mode: "cors",
      }).catch(function () {});
    } catch (e) {
      /* never break the host page */
    }
  }

  function schedule() {
    if (!elected()) return;
    var idle = window.requestIdleCallback || function (f) { return setTimeout(f, 1); };
    var go = function () { idle(harvest, { timeout: 4000 }); };
    if (document.readyState === "complete") go();
    else window.addEventListener("load", go, { once: true });
  }

  schedule();
})();
`;

const outPath = join(import.meta.dirname, "..", "public", "adaptive-harvest.js");
writeFileSync(outPath, bundle, "utf8");
console.log(`wrote ${outPath} (${(bundle.length / 1024).toFixed(1)} kb)`);
