// Codegen: emit the detector browser-IIFE sources as REAL functions so the
// snippet can run them without eval / new Function (works on strict-CSP sites).
//
// Each X_SCRIPT constant is a string whose VALUE is already valid browser JS:
//   "(() => { … /\b…/ … })()"
// Writing that value verbatim as code — wrapped in `() => ( … )` — gives a
// callable function with no runtime code-gen. The audit engine keeps using the
// string form; this is a second, eval-free view of the SAME source.
//
// Run: bun run scripts/gen-detectors.ts  (also runs as part of build:adaptive)
import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";

import { PAGE_AUDIT_SCRIPT } from "../src/lib/tests/scripts/pageAudit";
import { SECTIONS_SCRIPT } from "../src/lib/tests/scripts/sections";
import { TRUST_SIGNALS_SCRIPT } from "../src/lib/tests/scripts/trustSignals";
import { CTAS_SCRIPT } from "../src/lib/tests/scripts/ctas";
import { FORMS_SCRIPT } from "../src/lib/tests/scripts/forms";
import { NAVIGATION_SCRIPT } from "../src/lib/tests/scripts/navigation";

const REPO = join(dirname(new URL(import.meta.url).pathname), "..");

const detectors: Array<[string, string]> = [
  ["pageAuditRun", PAGE_AUDIT_SCRIPT],
  ["sectionsRun", SECTIONS_SCRIPT],
  ["trustSignalsRun", TRUST_SIGNALS_SCRIPT],
  ["ctasRun", CTAS_SCRIPT],
  ["formsRun", FORMS_SCRIPT],
  ["navigationRun", NAVIGATION_SCRIPT],
];

const header = `// AUTO-GENERATED by scripts/gen-detectors.ts — DO NOT EDIT BY HAND.
// The browser-evaluable detector sources (src/lib/tests/scripts/*) emitted as
// real, callable functions so the Angel snippet runs them without eval /
// new Function — i.e. it works under a strict Content-Security-Policy.
// Regenerate: bun run scripts/gen-detectors.ts
/* eslint-disable */
// @ts-nocheck
`;

const body = detectors
  .map(([name, src]) => `export const ${name}: () => any = () => (${src});`)
  .join("\n\n");

const out = join(REPO, "src/adaptive/detectors.generated.ts");
writeFileSync(out, `${header}\n${body}\n`);

console.log(`wrote ${out} (${detectors.length} detectors, eval-free)`);
