// Seed the adaptive tables with baseline data, generated from the SAME mappers
// the runtime uses (single source of truth):
//   - angel_sites: the demo + hubspot installs.
//   - angel_content_inventory: the demo fixture and the real HubSpot corpus,
//     via getDemoInventory() / mapGoldenToInventory().
//
// Prints idempotent SQL (upserts) to stdout. Apply it however you reach the DB:
//   bun run scripts/seed-adaptive.ts | psql "$DATABASE_URL"
//   # or paste the output into the Supabase SQL editor
//
// Re-runnable: every statement is an upsert, so seeding twice is a no-op.

import { readFileSync } from "node:fs";

import { getDemoInventory } from "../src/adaptive/inventory";
import { mapGoldenToInventory } from "../src/adaptive/crawler-inventory";
import type { ContentInventory } from "../src/adaptive/types";

type Row = {
  site_slug: string;
  slot: string;
  item_id: string;
  text: string | null;
  selector: string | null;
  meta: Record<string, string>;
};

function toRows(inv: ContentInventory): Row[] {
  const rows: Row[] = [];
  for (const [slot, items] of Object.entries(inv.slots)) {
    for (const item of items ?? []) {
      rows.push({
        site_slug: inv.site,
        slot,
        item_id: item.id,
        text: item.text ?? null,
        selector: item.selector ?? null,
        meta: item.meta ?? {},
      });
    }
  }
  return rows;
}

const demo = getDemoInventory();
const hubspotGolden: unknown = JSON.parse(readFileSync("corpus/hubspot/golden.json", "utf8"));
const hubspot = mapGoldenToInventory(hubspotGolden, "hubspot");

const rows = [...toRows(demo), ...toRows(hubspot)];
const json = JSON.stringify(rows);

const sql = `-- Generated by scripts/seed-adaptive.ts — do not edit by hand.
insert into public.angel_sites (slug, domain, name) values
  ('demo', null, 'Demo'),
  ('hubspot', 'hubspot.com', 'HubSpot')
on conflict (slug) do update set domain = excluded.domain, name = excluded.name;

insert into public.angel_content_inventory (site_slug, slot, item_id, text, selector, meta)
select site_slug, slot, item_id, text, selector, meta
from jsonb_to_recordset($seed$${json}$seed$::jsonb)
  as x(site_slug text, slot text, item_id text, text text, selector text, meta jsonb)
on conflict (site_slug, item_id) do update
  set text = excluded.text, selector = excluded.selector, meta = excluded.meta;
`;

console.log(sql);
