// Typed access to the Angel Adaptive tables via the service-role admin client.
// Row/Insert aliases are sourced from the generated Supabase types
// (src/integrations/supabase/types.ts), regenerated by `bun run db:types` after
// each migration.

import type { Tables, TablesInsert } from "@/integrations/supabase/types";

import { supabaseAdmin } from "@/integrations/supabase/client.server";

export const db = supabaseAdmin;

export type SiteRow = Tables<"sites">;
export type SessionRow = Tables<"sessions">;
export type EventRow = Tables<"events">;
export type RollupRow = Tables<"events_rollup">;

export type VisitorInsert = TablesInsert<"visitors">;
export type SessionInsert = TablesInsert<"sessions">;
export type EventInsert = TablesInsert<"events">;
export type RollupInsert = TablesInsert<"events_rollup">;

export type CrawlRunRow = Tables<"crawl_runs">;
export type ContentInventoryRow = Tables<"content_inventory">;
export type ContentInventoryInsert = TablesInsert<"content_inventory">;
