/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as CorpusRouteImport } from './routes/corpus'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAdaptiveEventsRouteImport } from './routes/api/adaptive/events'
import { Route as ApiAdaptiveDecideRouteImport } from './routes/api/adaptive/decide'
import { Route as ApiTestsRunIdStreamRouteImport } from './routes/api/tests/$runId.stream'
import { Route as ApiPublicCorpusSplatRouteImport } from './routes/api/public/corpus.$'

const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CorpusRoute = CorpusRouteImport.update({
  id: '/corpus',
  path: '/corpus',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdaptiveEventsRoute = ApiAdaptiveEventsRouteImport.update({
  id: '/api/adaptive/events',
  path: '/api/adaptive/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdaptiveDecideRoute = ApiAdaptiveDecideRouteImport.update({
  id: '/api/adaptive/decide',
  path: '/api/adaptive/decide',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestsRunIdStreamRoute = ApiTestsRunIdStreamRouteImport.update({
  id: '/api/tests/$runId/stream',
  path: '/api/tests/$runId/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCorpusSplatRoute = ApiPublicCorpusSplatRouteImport.update({
  id: '/api/public/corpus/$',
  path: '/api/public/corpus/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/corpus': typeof CorpusRoute
  '/demo': typeof DemoRoute
  '/api/adaptive/decide': typeof ApiAdaptiveDecideRoute
  '/api/adaptive/events': typeof ApiAdaptiveEventsRoute
  '/api/public/corpus/$': typeof ApiPublicCorpusSplatRoute
  '/api/tests/$runId/stream': typeof ApiTestsRunIdStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/corpus': typeof CorpusRoute
  '/demo': typeof DemoRoute
  '/api/adaptive/decide': typeof ApiAdaptiveDecideRoute
  '/api/adaptive/events': typeof ApiAdaptiveEventsRoute
  '/api/public/corpus/$': typeof ApiPublicCorpusSplatRoute
  '/api/tests/$runId/stream': typeof ApiTestsRunIdStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/corpus': typeof CorpusRoute
  '/demo': typeof DemoRoute
  '/api/adaptive/decide': typeof ApiAdaptiveDecideRoute
  '/api/adaptive/events': typeof ApiAdaptiveEventsRoute
  '/api/public/corpus/$': typeof ApiPublicCorpusSplatRoute
  '/api/tests/$runId/stream': typeof ApiTestsRunIdStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/corpus'
    | '/demo'
    | '/api/adaptive/decide'
    | '/api/adaptive/events'
    | '/api/public/corpus/$'
    | '/api/tests/$runId/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/corpus'
    | '/demo'
    | '/api/adaptive/decide'
    | '/api/adaptive/events'
    | '/api/public/corpus/$'
    | '/api/tests/$runId/stream'
  id:
    | '__root__'
    | '/'
    | '/corpus'
    | '/demo'
    | '/api/adaptive/decide'
    | '/api/adaptive/events'
    | '/api/public/corpus/$'
    | '/api/tests/$runId/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CorpusRoute: typeof CorpusRoute
  DemoRoute: typeof DemoRoute
  ApiAdaptiveDecideRoute: typeof ApiAdaptiveDecideRoute
  ApiAdaptiveEventsRoute: typeof ApiAdaptiveEventsRoute
  ApiPublicCorpusSplatRoute: typeof ApiPublicCorpusSplatRoute
  ApiTestsRunIdStreamRoute: typeof ApiTestsRunIdStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corpus': {
      id: '/corpus'
      path: '/corpus'
      fullPath: '/corpus'
      preLoaderRoute: typeof CorpusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/adaptive/events': {
      id: '/api/adaptive/events'
      path: '/api/adaptive/events'
      fullPath: '/api/adaptive/events'
      preLoaderRoute: typeof ApiAdaptiveEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/adaptive/decide': {
      id: '/api/adaptive/decide'
      path: '/api/adaptive/decide'
      fullPath: '/api/adaptive/decide'
      preLoaderRoute: typeof ApiAdaptiveDecideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tests/$runId/stream': {
      id: '/api/tests/$runId/stream'
      path: '/api/tests/$runId/stream'
      fullPath: '/api/tests/$runId/stream'
      preLoaderRoute: typeof ApiTestsRunIdStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/corpus/$': {
      id: '/api/public/corpus/$'
      path: '/api/public/corpus/$'
      fullPath: '/api/public/corpus/$'
      preLoaderRoute: typeof ApiPublicCorpusSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CorpusRoute: CorpusRoute,
  DemoRoute: DemoRoute,
  ApiAdaptiveDecideRoute: ApiAdaptiveDecideRoute,
  ApiAdaptiveEventsRoute: ApiAdaptiveEventsRoute,
  ApiPublicCorpusSplatRoute: ApiPublicCorpusSplatRoute,
  ApiTestsRunIdStreamRoute: ApiTestsRunIdStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
