/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CorpusRouteImport } from './routes/corpus'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTestsRunIdStreamRouteImport } from './routes/api/tests/$runId.stream'
import { Route as ApiPublicCorpusSplatRouteImport } from './routes/api/public/corpus.$'

const CorpusRoute = CorpusRouteImport.update({
  id: '/corpus',
  path: '/corpus',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestsRunIdStreamRoute = ApiTestsRunIdStreamRouteImport.update({
  id: '/api/tests/$runId/stream',
  path: '/api/tests/$runId/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCorpusSplatRoute = ApiPublicCorpusSplatRouteImport.update({
  id: '/api/public/corpus/$',
  path: '/api/public/corpus/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/corpus': typeof CorpusRoute
  '/api/public/corpus/$': typeof ApiPublicCorpusSplatRoute
  '/api/tests/$runId/stream': typeof ApiTestsRunIdStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/corpus': typeof CorpusRoute
  '/api/public/corpus/$': typeof ApiPublicCorpusSplatRoute
  '/api/tests/$runId/stream': typeof ApiTestsRunIdStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/corpus': typeof CorpusRoute
  '/api/public/corpus/$': typeof ApiPublicCorpusSplatRoute
  '/api/tests/$runId/stream': typeof ApiTestsRunIdStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/corpus'
    | '/api/public/corpus/$'
    | '/api/tests/$runId/stream'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/corpus' | '/api/public/corpus/$' | '/api/tests/$runId/stream'
  id:
    | '__root__'
    | '/'
    | '/corpus'
    | '/api/public/corpus/$'
    | '/api/tests/$runId/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CorpusRoute: typeof CorpusRoute
  ApiPublicCorpusSplatRoute: typeof ApiPublicCorpusSplatRoute
  ApiTestsRunIdStreamRoute: typeof ApiTestsRunIdStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/corpus': {
      id: '/corpus'
      path: '/corpus'
      fullPath: '/corpus'
      preLoaderRoute: typeof CorpusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tests/$runId/stream': {
      id: '/api/tests/$runId/stream'
      path: '/api/tests/$runId/stream'
      fullPath: '/api/tests/$runId/stream'
      preLoaderRoute: typeof ApiTestsRunIdStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/corpus/$': {
      id: '/api/public/corpus/$'
      path: '/api/public/corpus/$'
      fullPath: '/api/public/corpus/$'
      preLoaderRoute: typeof ApiPublicCorpusSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CorpusRoute: CorpusRoute,
  ApiPublicCorpusSplatRoute: ApiPublicCorpusSplatRoute,
  ApiTestsRunIdStreamRoute: ApiTestsRunIdStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
