/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicSpikeRouteImport } from './routes/api/public/spike'
import { Route as ApiTestsRunIdStreamRouteImport } from './routes/api/tests/$runId.stream'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSpikeRoute = ApiPublicSpikeRouteImport.update({
  id: '/api/public/spike',
  path: '/api/public/spike',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestsRunIdStreamRoute = ApiTestsRunIdStreamRouteImport.update({
  id: '/api/tests/$runId/stream',
  path: '/api/tests/$runId/stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/spike': typeof ApiPublicSpikeRoute
  '/api/tests/$runId/stream': typeof ApiTestsRunIdStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/spike': typeof ApiPublicSpikeRoute
  '/api/tests/$runId/stream': typeof ApiTestsRunIdStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/spike': typeof ApiPublicSpikeRoute
  '/api/tests/$runId/stream': typeof ApiTestsRunIdStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/spike' | '/api/tests/$runId/stream'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/spike' | '/api/tests/$runId/stream'
  id: '__root__' | '/' | '/api/public/spike' | '/api/tests/$runId/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicSpikeRoute: typeof ApiPublicSpikeRoute
  ApiTestsRunIdStreamRoute: typeof ApiTestsRunIdStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/spike': {
      id: '/api/public/spike'
      path: '/api/public/spike'
      fullPath: '/api/public/spike'
      preLoaderRoute: typeof ApiPublicSpikeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tests/$runId/stream': {
      id: '/api/tests/$runId/stream'
      path: '/api/tests/$runId/stream'
      fullPath: '/api/tests/$runId/stream'
      preLoaderRoute: typeof ApiTestsRunIdStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicSpikeRoute: ApiPublicSpikeRoute,
  ApiTestsRunIdStreamRoute: ApiTestsRunIdStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
